name: Deploy Website 
on:
    push:
        branches:
            - main
jobs:
    htmlbuild:
        name: Publish Recipes 
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: './'
        permissions:
          contents: write

        steps:
        - uses: actions/checkout@v4
        - name: Install Pandoc
          uses: pandoc/actions/setup@v1
          with: 
            version: 3.1.8
        - name: Install Python
          uses: actions/setup-python@v5
          with: 
            python-version: '3.11'
        - name: Install Jinja
          run: pip install Jinja2
        - name: Build project
          run: make build 
        - name: Move files
          run: |
            mkdir ../public
            mkdir ../public/tags
            mkdir ../public/recipes
            mkdir ../public/img
            mv ./html/* ../public
            mv ./html/recipes/* ../public/recipes
            mv ./html/tags/* ../public/tags
            mv ./html/img/* ../public/img
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: ../public
            branch: gh-pages
